remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: From Component to System A Task-Unified Planning System with Planning-Oriented Predictor
description: Jiahui Xu, Wenbo Shao, Weida Wang, Cheng Liu, Chao Yang, Jun Li and Hong Wang
show_downloads: false
